=== SantiagoDalchiele/logicgame/recursos/xsd/juego-logica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
	<element name="juego">
		<complexType>
			<sequence>
				<element name="id" type="integer"/>
				<element name="titulo" type="string"/>
				<element name="texto" type="string"/>
				<element name="costo" type="integer"/>
				<element name="dimensiones">
					<complexType>
						<sequence maxOccurs="unbounded">
							<element name="dimension">
								<complexType>
									<sequence>
										<element name="id" type="string"/>
										<element name="valores">
											<complexType>
												<sequence maxOccurs="unbounded">
													<element name="valor" type="string"/>
												</sequence>
											</complexType>
										</element>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
				<element name="pistas-del-juego">
					<complexType>
						<sequence maxOccurs="unbounded">
							<element name="pista-del-juego">
								<complexType>
									<sequence>
										<element name="texto" type="string"/>
										<element name="pistas">
											<complexType>
												<sequence maxOccurs="unbounded">
													<element name="pista">
														<complexType>
															<sequence>
																<element name="id-dimension1" type="string"/>
																<element name="id-valor1" type="string"/>
																<element name="id-dimension2" type="string"/>
																<element name="id-valor2" type="string"/>
																<element name="afirma-niega" type="boolean"/>																
															</sequence>
														</complexType>
													</element>
												</sequence>
											</complexType>
										</element>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== SantiagoDalchiele/logicgame/recursos/juegos/14-RiosYBanderas.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<juego xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/juego-logica.xsd">
	<id>14</id>
	<titulo>Ríos y banderas</titulo>
	<texto>Seguramente que ya sabes muchas cosas sobre países de Hispanoamérica, pero siempre se puede aprender más. En el juego de hoy tienes que relacionar los ríos Loa, Negro, Pilcomayo y Guayas con sus países respectivos (Paraguay, Chile, Ecuador y Uruguay), así como con	los símbolos de sus banderas (sol, estrella, pájaro y símbolo circular).</texto>
	<costo>20</costo>
	<dimensiones>
		<dimension>
			<id>País</id>
			<valores>
				<valor>Paraguay</valor>
				<valor>Chile</valor>
				<valor>Ecuador</valor>
				<valor>Uruguay</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Bandera</id>
			<valores>
				<valor>sol</valor>
				<valor>estrella</valor>
				<valor>pájaro</valor>
				<valor>símbolo circular</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Río</id>
			<valores>
				<valor>Loa</valor>
				<valor>Negro</valor>
				<valor>Pilcomayo</valor>
				<valor>Guayas</valor>
			</valores>
		</dimension>
	</dimensiones>
	<pistas-del-juego>
		<pista-del-juego>
			<texto>El sol no está en la bandera de Ecuador</texto>
			<pistas>
				<pista>
					<id-dimension1>Bandera</id-dimension1>
					<id-valor1>sol</id-valor1>
					<id-dimension2>País</id-dimension2>
					<id-valor2>Ecuador</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>En Paraguay está el río Pilcomayo</texto>
			<pistas>
				<pista>
					<id-dimension1>País</id-dimension1>
					<id-valor1>Paraguay</id-valor1>
					<id-dimension2>Río</id-dimension2>
					<id-valor2>Pilcomayo</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>En la bandera de Uruguay no hay una estrella ni un símbolo
				circular</texto>
			<pistas>
				<pista>
					<id-dimension1>País</id-dimension1>
					<id-valor1>Uruguay</id-valor1>
					<id-dimension2>Bandera</id-dimension2>
					<id-valor2>estrella</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>País</id-dimension1>
					<id-valor1>Uruguay</id-valor1>
					<id-dimension2>Bandera</id-dimension2>
					<id-valor2>símbolo circular</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El río Negro no está en Ecuador ni en Chile</texto>
			<pistas>
				<pista>
					<id-dimension1>Río</id-dimension1>
					<id-valor1>Negro</id-valor1>
					<id-dimension2>País</id-dimension2>
					<id-valor2>Ecuador</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Río</id-dimension1>
					<id-valor1>Negro</id-valor1>
					<id-dimension2>País</id-dimension2>
					<id-valor2>Chile</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>La estrella está en la bandera de Chile</texto>
			<pistas>
				<pista>
					<id-dimension1>Bandera</id-dimension1>
					<id-valor1>estrella</id-valor1>
					<id-dimension2>País</id-dimension2>
					<id-valor2>Chile</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El río Loa no está en Ecuador</texto>
			<pistas>
				<pista>
					<id-dimension1>Río</id-dimension1>
					<id-valor1>Loa</id-valor1>
					<id-dimension2>País</id-dimension2>
					<id-valor2>Ecuador</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El pájaro no está en la bandera de Paraguay ni en la de
				Uruguay</texto>
			<pistas>
				<pista>
					<id-dimension1>Bandera</id-dimension1>
					<id-valor1>pájaro</id-valor1>
					<id-dimension2>País</id-dimension2>
					<id-valor2>Paraguay</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Bandera</id-dimension1>
					<id-valor1>pájaro</id-valor1>
					<id-dimension2>País</id-dimension2>
					<id-valor2>Uruguay</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El río Guayas no está en Chile</texto>
			<pistas>
				<pista>
					<id-dimension1>Río</id-dimension1>
					<id-valor1>Guayas</id-valor1>
					<id-dimension2>País</id-dimension2>
					<id-valor2>Chile</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
	</pistas-del-juego>
</juego>

=== SantiagoDalchiele/logicgame/recursos/juegos/13-hispanoamerica-recursos.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<juego xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/juego-logica.xsd">
	<id>13</id>
	<titulo>Hispanoamérica y su economía</titulo>
	<texto>Los países hispanoamericanos tienen un enorme potencial económico. Hoy vamos a conocer algunas de sus riquezas más importantes en varios sectores de la economía. Pero para conseguir esta información debes leer atentamente las pistas que te damos</texto>
	<costo>88</costo>
	<dimensiones>
		<dimension>
			<id>País</id>
			<valores>
				<valor>Costa Rica</valor>
				<valor>Cuba</valor>
				<valor>Chile</valor>
				<valor>Ecuador</valor>
				<valor>Guatemala</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Agricultura</id>
			<valores>
				<valor>maíz</valor>
				<valor>caña de azúcar</valor>
				<valor>trigo</valor>
				<valor>algodón</valor>
				<valor>plátano</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Minería</id>
			<valores>
				<valor>bauxita</valor>
				<valor>níquel</valor>
				<valor>cobre</valor>
				<valor>oro</valor>
				<valor>zinc</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Industria</id>
			<valores>
				<valor>maquinaria</valor>
				<valor>tabaco</valor>
				<valor>siderurgia</valor>
				<valor>tejido</valor>
				<valor>alimentos</valor>
			</valores>
		</dimension>
	</dimensiones>
	<pistas-del-juego>
		<pista-del-juego>
			<texto>El país andino utiliza en su bandera el color amarillo, que recuerda sus importantes yacimientos de oro</texto>
			<pistas>
				<pista>
					<id-dimension1>País</id-dimension1>
					<id-valor1>Ecuador</id-valor1>
					<id-dimension2>Minería</id-dimension2>
					<id-valor2>oro</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>La caña de azúcar es el más importante producto agrícola de la mayor de las islas de las Antillas</texto>
			<pistas>
				<pista>
					<id-dimension1>Agricultura</id-dimension1>
					<id-valor1>caña de azúcar</id-valor1>
					<id-dimension2>País</id-dimension2>
					<id-valor2>Cuba</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Costa Rica posee grandes plantaciones de maíz</texto>
			<pistas>
				<pista>
					<id-dimension1>País</id-dimension1>
					<id-valor1>Costa Rica</id-valor1>
					<id-dimension2>Agricultura</id-dimension2>
					<id-valor2>maíz</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Cuba produce, fabrica y exporta tabaco de gran calidad</texto>
			<pistas>
				<pista>
					<id-dimension1>País</id-dimension1>
					<id-valor1>Cuba</id-valor1>
					<id-dimension2>Industria</id-dimension2>
					<id-valor2>tabaco</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Chile, con su clima templado, tiene excelentes tierras para la siembra de trigo y ricas minas de cobre</texto>
			<pistas>
				<pista>
					<id-dimension1>País</id-dimension1>
					<id-valor1>Chile</id-valor1>
					<id-dimension2>Agricultura</id-dimension2>
					<id-valor2>trigo</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>País</id-dimension1>
					<id-valor1>Chile</id-valor1>
					<id-dimension2>Minería</id-dimension2>
					<id-valor2>cobre</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Ecuador destaca por sus algodonales, que le han permitido desarrollar una importante industria textil</texto>
			<pistas>
				<pista>
					<id-dimension1>País</id-dimension1>
					<id-valor1>Ecuador</id-valor1>
					<id-dimension2>Agricultura</id-dimension2>
					<id-valor2>algodón</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>País</id-dimension1>
					<id-valor1>Ecuador</id-valor1>
					<id-dimension2>Industria</id-dimension2>
					<id-valor2>tejido</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Los guatemaltecos dedican sus tierras a la siembra del plátano y su industria a los alimentos en general</texto>
			<pistas>
				<pista>
					<id-dimension1>País</id-dimension1>
					<id-valor1>Guatemala</id-valor1>
					<id-dimension2>Agricultura</id-dimension2>
					<id-valor2>plátano</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>País</id-dimension1>
					<id-valor1>Guatemala</id-valor1>
					<id-dimension2>Industria</id-dimension2>
					<id-valor2>alimentos</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El país caribeño posee grandes yacimientos de níquel</texto>
			<pistas>
				<pista>
					<id-dimension1>País</id-dimension1>
					<id-valor1>Cuba</id-valor1>
					<id-dimension2>Minería</id-dimension2>
					<id-valor2>níquel</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El cobre ha permitido a este País sudamericano desarrollar la siderurgia</texto>
			<pistas>
				<pista>
					<id-dimension1>Minería</id-dimension1>
					<id-valor1>cobre</id-valor1>
					<id-dimension2>Industria</id-dimension2>
					<id-valor2>siderurgia</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Guatemala tiene un gran recurso minero: el zinc</texto>
			<pistas>
				<pista>
					<id-dimension1>País</id-dimension1>
					<id-valor1>Guatemala</id-valor1>
					<id-dimension2>Minería</id-dimension2>
					<id-valor2>zinc</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>La bauxita es un mineral de gran importancia en el país centroamericano, que, además, produce maquinaria para la industria</texto>
			<pistas>
				<pista>
					<id-dimension1>Minería</id-dimension1>
					<id-valor1>bauxita</id-valor1>
					<id-dimension2>Industria</id-dimension2>
					<id-valor2>maquinaria</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
	</pistas-del-juego>
</juego>
