=== SantiagoDalchiele/logicgame/recursos/xsd/juego-logica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
	<element name="juego">
		<complexType>
			<sequence>
				<element name="id" type="integer"/>
				<element name="titulo" type="string"/>
				<element name="texto" type="string"/>
				<element name="costo" type="integer"/>
				<element name="dimensiones">
					<complexType>
						<sequence maxOccurs="unbounded">
							<element name="dimension">
								<complexType>
									<sequence>
										<element name="id" type="string"/>
										<element name="valores">
											<complexType>
												<sequence maxOccurs="unbounded">
													<element name="valor" type="string"/>
												</sequence>
											</complexType>
										</element>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
				<element name="pistas-del-juego">
					<complexType>
						<sequence maxOccurs="unbounded">
							<element name="pista-del-juego">
								<complexType>
									<sequence>
										<element name="texto" type="string"/>
										<element name="pistas">
											<complexType>
												<sequence maxOccurs="unbounded">
													<element name="pista">
														<complexType>
															<sequence>
																<element name="id-dimension1" type="string"/>
																<element name="id-valor1" type="string"/>
																<element name="id-dimension2" type="string"/>
																<element name="id-valor2" type="string"/>
																<element name="afirma-niega" type="boolean"/>																
															</sequence>
														</complexType>
													</element>
												</sequence>
											</complexType>
										</element>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== SantiagoDalchiele/logicgame/recursos/juegos/21-turistas-en-uruguay.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<juego xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/juego-logica.xsd">
	<id>21</id>
	<titulo>Turistas de vacaciones en Uruguay</titulo>
	<texto>Averigua que balneario visita cada turista según su nacionalidad, donde se hospedan cada uno de ellos, por cuantos días, quienes los acompañan en su estadía y cuál es su entretenimiento favorito</texto>
	<costo>687</costo>
	<dimensiones>
		<dimension>
			<id>Nacionalidad</id>
			<valores>
				<valor>español</valor>
				<valor>argentino</valor>
				<valor>brasileño</valor>
				<valor>paraguayo</valor>
				<valor>chileno</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Balneario</id>
			<valores>
				<valor>Punta del Este</valor>
				<valor>Piriápolis</valor>
				<valor>La Paloma</valor>
				<valor>Punta del Diablo</valor>
				<valor>Atlantida</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Hospedaje</id>
			<valores>
				<valor>casa</valor>
				<valor>apartamento</valor>
				<valor>hotel</valor>
				<valor>camping</valor>
				<valor>hostel</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Días</id>
			<valores>
				<valor>4</valor>
				<valor>7</valor>
				<valor>10</valor>
				<valor>14</valor>
				<valor>15</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Acompañado</id>
			<valores>
				<valor>primos</valor>
				<valor>pareja</valor>
				<valor>hijos</valor>
				<valor>amigos</valor>
				<valor>padres</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Entretenimiento</id>
			<valores>
				<valor>surf</valor>
				<valor>navegar</valor>
				<valor>senderismo</valor>
				<valor>volleyball</valor>
				<valor>cabalgar</valor>
			</valores>
		</dimension>
	</dimensiones>
	<pistas-del-juego>
		<pista-del-juego>
			<texto>Quien viaja acompañado por amigos es argentino y le encanta el surf</texto>
			<pistas>
				<pista>
					<id-dimension1>Acompañado</id-dimension1>
					<id-valor1>amigos</id-valor1>
					<id-dimension2>Nacionalidad</id-dimension2>
					<id-valor2>argentino</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Acompañado</id-dimension1>
					<id-valor1>amigos</id-valor1>
					<id-dimension2>Entretenimiento</id-dimension2>
					<id-valor2>surf</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien viaja acompañado por sus hijos es brasileño</texto>
			<pistas>
				<pista>
					<id-dimension1>Acompañado</id-dimension1>
					<id-valor1>hijos</id-valor1>
					<id-dimension2>Nacionalidad</id-dimension2>
					<id-valor2>brasileño</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien viaja por la menor cantidad de días visita Punta del Este</texto>
			<pistas>
				<pista>
					<id-dimension1>Días</id-dimension1>
					<id-valor1>4</id-valor1>
					<id-dimension2>Balneario</id-dimension2>
					<id-valor2>Punta del Este</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien visita el país por 14 días no es argentino</texto>
			<pistas>
				<pista>
					<id-dimension1>Días</id-dimension1>
					<id-valor1>14</id-valor1>
					<id-dimension2>Nacionalidad</id-dimension2>
					<id-valor2>argentino</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien visita el país por 10 días es chileno, pero no le gusta navegar</texto>
			<pistas>
				<pista>
					<id-dimension1>Días</id-dimension1>
					<id-valor1>10</id-valor1>
					<id-dimension2>Nacionalidad</id-dimension2>
					<id-valor2>chileno</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Días</id-dimension1>
					<id-valor1>10</id-valor1>
					<id-dimension2>Entretenimiento</id-dimension2>
					<id-valor2>navegar</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El paraguayo se hospeda en un camping en Punta del Diablo</texto>
			<pistas>
				<pista>
					<id-dimension1>Nacionalidad</id-dimension1>
					<id-valor1>paraguayo</id-valor1>
					<id-dimension2>Hospedaje</id-dimension2>
					<id-valor2>camping</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Balneario</id-dimension1>
					<id-valor1>Punta del Diablo</id-valor1>
					<id-dimension2>Nacionalidad</id-dimension2>
					<id-valor2>paraguayo</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien gusta de navegar se hospeda en una casa en el balneario La Paloma.  Su estadía no es de 14 días</texto>
			<pistas>
				<pista>
					<id-dimension1>Hospedaje</id-dimension1>
					<id-valor1>casa</id-valor1>
					<id-dimension2>Balneario</id-dimension2>
					<id-valor2>La Paloma</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Balneario</id-dimension1>
					<id-valor1>La Paloma</id-valor1>
					<id-dimension2>Días</id-dimension2>
					<id-valor2>14</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Entretenimiento</id-dimension1>
					<id-valor1>navegar</id-valor1>
					<id-dimension2>Balneario</id-dimension2>
					<id-valor2>La Paloma</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien viaja con sus primos se quedará la mayor cantidad de días en Uruguay</texto>
			<pistas>
				<pista>
					<id-dimension1>Acompañado</id-dimension1>
					<id-valor1>primos</id-valor1>
					<id-dimension2>Días</id-dimension2>
					<id-valor2>15</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El argentino no visitará Punta del Este</texto>
			<pistas>
				<pista>
					<id-dimension1>Nacionalidad</id-dimension1>
					<id-valor1>argentino</id-valor1>
					<id-dimension2>Balneario</id-dimension2>
					<id-valor2>Punta del Este</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El senderismo es preferido por quien se hospeda en un apartamento, que no es el chileno</texto>
			<pistas>
				<pista>
					<id-dimension1>Entretenimiento</id-dimension1>
					<id-valor1>senderismo</id-valor1>
					<id-dimension2>Hospedaje</id-dimension2>
					<id-valor2>apartamento</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Nacionalidad</id-dimension1>
					<id-valor1>chileno</id-valor1>
					<id-dimension2>Entretenimiento</id-dimension2>
					<id-valor2>senderismo</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien elige un hostel, no le gusta el volleyball</texto>
			<pistas>
				<pista>
					<id-dimension1>Hospedaje</id-dimension1>
					<id-valor1>hostel</id-valor1>
					<id-dimension2>Entretenimiento</id-dimension2>
					<id-valor2>volleyball</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El volleyball es el entretenimiento preferido de quien viaja acompañado por sus padres y visita Atlantida</texto>
			<pistas>
				<pista>
					<id-dimension1>Entretenimiento</id-dimension1>
					<id-valor1>volleyball</id-valor1>
					<id-dimension2>Acompañado</id-dimension2>
					<id-valor2>padres</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Entretenimiento</id-dimension1>
					<id-valor1>volleyball</id-valor1>
					<id-dimension2>Balneario</id-dimension2>
					<id-valor2>Atlantida</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
	</pistas-del-juego>
</juego>

=== SantiagoDalchiele/logicgame/recursos/juegos/20-casamientos.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<juego xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/juego-logica.xsd">
	<id>20</id>
	<titulo>Casamientos</titulo>
	<texto>5 mujeres se casan con sus respectivos esposos, descubre que material resalta en sus joyas, de que color eligió su vestido y en que ciudad pasarán su luna de miel</texto>
	<costo>353</costo>
	<dimensiones>
		<dimension>
			<id>Nombre</id>
			<valores>
				<valor>Bárbara</valor>
				<valor>Pamela</valor>
				<valor>Victoria</valor>
				<valor>Claudia</valor>
				<valor>Jimena</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Marido</id>
			<valores>
				<valor>Maximiliano</valor>
				<valor>Roberto</valor>
				<valor>Ignacio</valor>
				<valor>Renzo</valor>
				<valor>Osvaldo</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Joya</id>
			<valores>
				<valor>oro</valor>
				<valor>plata</valor>
				<valor>diamante</valor>
				<valor>zafiro</valor>
				<valor>esmeralda</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Vestido</id>
			<valores>
				<valor>blanco</valor>
				<valor>marfil</valor>
				<valor>beige</valor>
				<valor>champagne</valor>
				<valor>crema</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Ciudad</id>
			<valores>
				<valor>Florencia</valor>
				<valor>Venecia</valor>
				<valor>París</valor>
				<valor>New York</valor>
				<valor>Viena</valor>
			</valores>
		</dimension>
	</dimensiones>
	<pistas-del-juego>
		<pista-del-juego>
			<texto>Victoria, quien se vá de luna de miel a Viena, no tiene ni una esmeralda ni un zafiro en su joya</texto>
			<pistas>
				<pista>
					<id-dimension1>Ciudad</id-dimension1>
					<id-valor1>Viena</id-valor1>
					<id-dimension2>Joya</id-dimension2>
					<id-valor2>esmeralda</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Victoria</id-valor1>
					<id-dimension2>Ciudad</id-dimension2>
					<id-valor2>Viena</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Ciudad</id-dimension1>
					<id-valor1>Viena</id-valor1>
					<id-dimension2>Joya</id-dimension2>
					<id-valor2>zafiro</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Claudia elige New York para su luna de miel y recibe un hermoso anillo de oro puro</texto>
			<pistas>
				<pista>
					<id-dimension1>Ciudad</id-dimension1>
					<id-valor1>New York</id-valor1>
					<id-dimension2>Nombre</id-dimension2>
					<id-valor2>Claudia</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Claudia</id-valor1>
					<id-dimension2>Joya</id-dimension2>
					<id-valor2>oro</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Pamela se niega a usar un vestido color champagne</texto>
			<pistas>
				<pista>
					<id-dimension1>Vestido</id-dimension1>
					<id-valor1>champagne</id-valor1>
					<id-dimension2>Nombre</id-dimension2>
					<id-valor2>Pamela</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Bárbara, la del vestido beige, no se casa con Osvaldo</texto>
			<pistas>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Bárbara</id-valor1>
					<id-dimension2>Marido</id-dimension2>
					<id-valor2>Osvaldo</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Vestido</id-dimension1>
					<id-valor1>beige</id-valor1>
					<id-dimension2>Nombre</id-dimension2>
					<id-valor2>Bárbara</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Pamela y su futuro marido Roberto no optaron por pasar su luna de miel en París</texto>
			<pistas>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Pamela</id-valor1>
					<id-dimension2>Marido</id-dimension2>
					<id-valor2>Roberto</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Pamela</id-valor1>
					<id-dimension2>Ciudad</id-dimension2>
					<id-valor2>París</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Jimena sueña con su luna de miel en Venecia, pero no le gusta el color marfil para su vestido, ni las esmeraldas</texto>
			<pistas>
				<pista>
					<id-dimension1>Ciudad</id-dimension1>
					<id-valor1>Venecia</id-valor1>
					<id-dimension2>Joya</id-dimension2>
					<id-valor2>esmeralda</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Ciudad</id-dimension1>
					<id-valor1>Venecia</id-valor1>
					<id-dimension2>Vestido</id-dimension2>
					<id-valor2>marfil</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Ciudad</id-dimension1>
					<id-valor1>Venecia</id-valor1>
					<id-dimension2>Nombre</id-dimension2>
					<id-valor2>Jimena</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien se casará con Renzo usa un vestido crema, pero no tiene la joya hecha en plata</texto>
			<pistas>
				<pista>
					<id-dimension1>Marido</id-dimension1>
					<id-valor1>Renzo</id-valor1>
					<id-dimension2>Joya</id-dimension2>
					<id-valor2>plata</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Marido</id-dimension1>
					<id-valor1>Renzo</id-valor1>
					<id-dimension2>Vestido</id-dimension2>
					<id-valor2>crema</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien usa la joya con una piedra de zafiro no usa el vestido de color beige ni marfil y no es Jimena</texto>
			<pistas>
				<pista>
					<id-dimension1>Joya</id-dimension1>
					<id-valor1>zafiro</id-valor1>
					<id-dimension2>Vestido</id-dimension2>
					<id-valor2>beige</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Joya</id-dimension1>
					<id-valor1>zafiro</id-valor1>
					<id-dimension2>Nombre</id-dimension2>
					<id-valor2>Jimena</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Joya</id-dimension1>
					<id-valor1>zafiro</id-valor1>
					<id-dimension2>Vestido</id-dimension2>
					<id-valor2>marfil</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Jimena quien se casa con Maximiliano no recibirá la joya hecha en plata</texto>
			<pistas>
				<pista>
					<id-dimension1>Marido</id-dimension1>
					<id-valor1>Maximiliano</id-valor1>
					<id-dimension2>Nombre</id-dimension2>
					<id-valor2>Jimena</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Marido</id-dimension1>
					<id-valor1>Maximiliano</id-valor1>
					<id-dimension2>Joya</id-dimension2>
					<id-valor2>plata</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
	</pistas-del-juego>
</juego>

=== SantiagoDalchiele/logicgame/recursos/juegos/07-gustos-literarios.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<juego xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/juego-logica.xsd">
	<id>7</id>
	<titulo>Gustos literarios</titulo>
	<texto>Descubre los gustos literarios de estos 4 personajes y sus profesiones</texto>
	<costo>24</costo>
	<dimensiones>
		<dimension>
			<id>Nombre</id>
			<valores>
				<valor>Arturo</valor>
				<valor>Carlos</valor>
				<valor>Juan</valor>
				<valor>Luis</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Profesión</id>
			<valores>
				<valor>Empresario</valor>
				<valor>Jardinero</valor>
				<valor>Mecánico</valor>
				<valor>Médico</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Género</id>
			<valores>
				<valor>Cuentos</valor>
				<valor>Novela</valor>
				<valor>Poesía</valor>
				<valor>Teatro</valor>
			</valores>
		</dimension>
	</dimensiones>
	<pistas-del-juego>
		<pista-del-juego>
			<texto>El médico no se llama Carlos y no le gusta la poesía</texto>
			<pistas>
				<pista>
					<id-dimension1>Profesión</id-dimension1>
					<id-valor1>Médico</id-valor1>
					<id-dimension2>Nombre</id-dimension2>
					<id-valor2>Carlos</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Profesión</id-dimension1>
					<id-valor1>Médico</id-valor1>
					<id-dimension2>Género</id-dimension2>
					<id-valor2>Poesía</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Luis no es médico ni empresario</texto>
			<pistas>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Luis</id-valor1>
					<id-dimension2>Profesión</id-dimension2>
					<id-valor2>Médico</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Luis</id-valor1>
					<id-dimension2>Profesión</id-dimension2>
					<id-valor2>Empresario</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Al que le gustan los cuentos no es mecánico</texto>
			<pistas>
				<pista>
					<id-dimension1>Género</id-dimension1>
					<id-valor1>Cuentos</id-valor1>
					<id-dimension2>Profesión</id-dimension2>
					<id-valor2>Mecánico</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Arturo es jardinero y no le gusta el teatro</texto>
			<pistas>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Arturo</id-valor1>
					<id-dimension2>Profesión</id-dimension2>
					<id-valor2>Jardinero</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Arturo</id-valor1>
					<id-dimension2>Género</id-dimension2>
					<id-valor2>Teatro</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Al médico le gustan los cuentos</texto>
			<pistas>
				<pista>
					<id-dimension1>Profesión</id-dimension1>
					<id-valor1>Médico</id-valor1>
					<id-dimension2>Género</id-dimension2>
					<id-valor2>Cuentos</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Al empresario le encanta la novela</texto>
			<pistas>
				<pista>
					<id-dimension1>Profesión</id-dimension1>
					<id-valor1>Empresario</id-valor1>
					<id-dimension2>Género</id-dimension2>
					<id-valor2>Novela</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
	</pistas-del-juego>
</juego>

=== SantiagoDalchiele/logicgame/recursos/juegos/04-esoterico.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<juego xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/juego-logica.xsd">
	<id>4</id>
	<titulo>Esot\u00E9rico</titulo>
	<texto>A pesar del misterio que rodea a la vidente Virginia, su jornada laboral se puede deducir leyendo cinco apuntes - los de abajo - sacados de su agenda.  Relacione los datos en el gr\u00E1fico y adivine la hora de cita de los clientes, los temas de sus consultas y las herramientas m\u00E1gicas que piensa utilizar</texto>
	<costo>105</costo>
	<dimensiones>
		<dimension>
			<id>Cliente</id>
			<valores>
				<valor>Amalia</valor>
				<valor>Benito</valor>
				<valor>Jos\u00E9</valor>
				<valor>Matilde</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Hora</id>
			<valores>
				<valor>16:00</valor>
				<valor>16:30</valor>
				<valor>17:00</valor>
				<valor>17:30</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Herramienta</id>
			<valores>
				<valor>Bola de cristal</valor>
				<valor>Posos</valor>
				<valor>Tarot</valor>
				<valor>Velas</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Temas</id>
			<valores>
				<valor>Amores</valor>
				<valor>Dinero</valor>
				<valor>Familia</valor>
				<valor>Salud</valor>
			</valores>
		</dimension>
	</dimensiones>
	<pistas-del-juego>
		<pista-del-juego>
			<texto>En la cita concertada con Matilde, indagar\u00E9 sobre sus futuros amores</texto>
			<pistas>
				<pista>
					<id-dimension1>Cliente</id-dimension1>
					<id-valor1>Matilde</id-valor1>
					<id-dimension2>Temas</id-dimension2>
					<id-valor2>Amores</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Para la entrevista de las 17:00 horas, me servir\u00E9 de la bola de cristal</texto>
			<pistas>
				<pista>
					<id-dimension1>Hora</id-dimension1>
					<id-valor1>17:00</id-valor1>
					<id-dimension2>Herramienta</id-dimension2>
					<id-valor2>Bola de cristal</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El tarot lo utilizar\u00E9 antes de atender a Jos\u00E9 y despu\u00E9s de responder al cliente preocupado por cuestiones de dinero</texto>
			<pistas>
				<pista>
					<id-dimension1>Herramienta</id-dimension1>
					<id-valor1>Tarot</id-valor1>
					<id-dimension2>Cliente</id-dimension2>
					<id-valor2>Jos\u00E9</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Herramienta</id-dimension1>
					<id-valor1>Tarot</id-valor1>
					<id-dimension2>Temas</id-dimension2>
					<id-valor2>Dinero</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Cliente</id-dimension1>
					<id-valor1>Jos\u00E9</id-valor1>
					<id-dimension2>Hora</id-dimension2>
					<id-valor2>16:00</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Cliente</id-dimension1>
					<id-valor1>Jos\u00E9</id-valor1>
					<id-dimension2>Hora</id-dimension2>
					<id-valor2>16:30</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Cliente</id-dimension1>
					<id-valor1>Jos\u00E9</id-valor1>
					<id-dimension2>Temas</id-dimension2>
					<id-valor2>Dinero</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Temas</id-dimension1>
					<id-valor1>Dinero</id-valor1>
					<id-dimension2>Hora</id-dimension2>
					<id-valor2>17:00</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Temas</id-dimension1>
					<id-valor1>Dinero</id-valor1>
					<id-dimension2>Hora</id-dimension2>
					<id-valor2>17:30</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Herramienta</id-dimension1>
					<id-valor1>Tarot</id-valor1>
					<id-dimension2>Hora</id-dimension2>
					<id-valor2>16:00</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Herramienta</id-dimension1>
					<id-valor1>Tarot</id-valor1>
					<id-dimension2>Hora</id-dimension2>
					<id-valor2>17:30</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Para responder a las preguntas de quien acude por temas de familia, recurrir\u00E9 a las velas</texto>
			<pistas>
				<pista>
					<id-dimension1>Temas</id-dimension1>
					<id-valor1>Familia</id-valor1>
					<id-dimension2>Herramienta</id-dimension2>
					<id-valor2>Velas</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Benito viene por motivos de salud. No le atender\u00E9 a las 16:30</texto>
			<pistas>
				<pista>
					<id-dimension1>Cliente</id-dimension1>
					<id-valor1>Benito</id-valor1>
					<id-dimension2>Temas</id-dimension2>
					<id-valor2>Salud</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Cliente</id-dimension1>
					<id-valor1>Benito</id-valor1>
					<id-dimension2>Hora</id-dimension2>
					<id-valor2>16:30</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
	</pistas-del-juego>
</juego>
