=== SantiagoDalchiele/logicgame/recursos/xsd/juego-logica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
	<element name="juego">
		<complexType>
			<sequence>
				<element name="id" type="integer"/>
				<element name="titulo" type="string"/>
				<element name="texto" type="string"/>
				<element name="costo" type="integer"/>
				<element name="dimensiones">
					<complexType>
						<sequence maxOccurs="unbounded">
							<element name="dimension">
								<complexType>
									<sequence>
										<element name="id" type="string"/>
										<element name="valores">
											<complexType>
												<sequence maxOccurs="unbounded">
													<element name="valor" type="string"/>
												</sequence>
											</complexType>
										</element>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
				<element name="pistas-del-juego">
					<complexType>
						<sequence maxOccurs="unbounded">
							<element name="pista-del-juego">
								<complexType>
									<sequence>
										<element name="texto" type="string"/>
										<element name="pistas">
											<complexType>
												<sequence maxOccurs="unbounded">
													<element name="pista">
														<complexType>
															<sequence>
																<element name="id-dimension1" type="string"/>
																<element name="id-valor1" type="string"/>
																<element name="id-dimension2" type="string"/>
																<element name="id-valor2" type="string"/>
																<element name="afirma-niega" type="boolean"/>																
															</sequence>
														</complexType>
													</element>
												</sequence>
											</complexType>
										</element>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== SantiagoDalchiele/logicgame/recursos/juegos/05-ropa-prestada.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<juego xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/juego-logica.xsd">
	<!-- No utilizar tiene más de una solución -->
	<id>5</id>
	<titulo>Ropa prestada</titulo>
	<texto></texto>
	<costo>70</costo>
	<dimensiones>
		<dimension>
			<id>Amiga</id>
			<valores>
				<valor>Almudena</valor>
				<valor>Ester</valor>
				<valor>Pilar</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Prenda</id>
			<valores>
				<valor>falda</valor>
				<valor>camisa</valor>
				<valor>jersey</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Material</id>
			<valores>
				<valor>tergal</valor>
				<valor>lana</valor>
				<valor>piel</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Color</id>
			<valores>
				<valor>negro</valor>
				<valor>blanca</valor>
				<valor>rosa</valor>
			</valores>
		</dimension>
	</dimensiones>
	<pistas-del-juego>
		<pista-del-juego>
			<texto>La falda es de color negro</texto>
			<pistas>
				<pista>
					<id-dimension1>Prenda</id-dimension1>
					<id-valor1>falda</id-valor1>
					<id-dimension2>Color</id-dimension2>
					<id-valor2>negro</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>La camisa es de tergal</texto>
			<pistas>
				<pista>
					<id-dimension1>Prenda</id-dimension1>
					<id-valor1>camisa</id-valor1>
					<id-dimension2>Material</id-dimension2>
					<id-valor2>tergal</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>La prenda que le ha dejado Almudena es de lana</texto>
			<pistas>
				<pista>
					<id-dimension1>Amiga</id-dimension1>
					<id-valor1>Almudena</id-valor1>
					<id-dimension2>Material</id-dimension2>
					<id-valor2>lana</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Almudena no le ha dejado la camisa</texto>
			<pistas>
				<pista>
					<id-dimension1>Amiga</id-dimension1>
					<id-valor1>Almudena</id-valor1>
					<id-dimension2>Prenda</id-dimension2>
					<id-valor2>camisa</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Ester le ha dejado una prenda blanca</texto>
			<pistas>
				<pista>
					<id-dimension1>Amiga</id-dimension1>
					<id-valor1>Ester</id-valor1>
					<id-dimension2>Color</id-dimension2>
					<id-valor2>blanca</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El jersey es rosa</texto>
			<pistas>
				<pista>
					<id-dimension1>Prenda</id-dimension1>
					<id-valor1>jersey</id-valor1>
					<id-dimension2>Color</id-dimension2>
					<id-valor2>rosa</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Pilar le ha dejado una prenda de piel</texto>
			<pistas>
				<pista>
					<id-dimension1>Amiga</id-dimension1>
					<id-valor1>Pilar</id-valor1>
					<id-dimension2>Material</id-dimension2>
					<id-valor2>piel</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
	</pistas-del-juego>
</juego>

=== SantiagoDalchiele/logicgame/recursos/juegos/03-vacaciones-islas.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<juego xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/juego-logica.xsd">
	<id>3</id>
	<titulo>Vacaciones en las islas</titulo>
	<texto>Descubre a que isla viajar\u00E1 cada una de las 4 amigas, en que compa\u00F1\u00EDa a\u00E9rea y cuantos d\u00EDas durar\u00E1 su estad\u00EDa</texto>
	<costo>156</costo>
	<dimensiones>
		<dimension>
			<id>Nombre</id>
			<valores>
				<valor>Carolina</valor>
				<valor>Diana</valor>
				<valor>Luisa</valor>
				<valor>Mar\u00EDa</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Isla</id>
			<valores>
				<valor>Ibiza</valor>
				<valor>Lanzarote</valor>
				<valor>Mallorca</valor>
				<valor>Tenerife</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Compa\u00F1ia</id>
			<valores>
				<valor>Air France</valor>
				<valor>Iberia</valor>
				<valor>Lufthansa</valor>
				<valor>Sabena</valor>
			</valores>
		</dimension>
		<dimension>
			<id>D\u00EDas</id>
			<valores>
				<valor>7</valor>
				<valor>10</valor>
				<valor>14</valor>
				<valor>15</valor>
			</valores>
		</dimension>
	</dimensiones>
	<pistas-del-juego>
		<pista-del-juego>
			<texto>Diana ha planeado ir a Lanzarote</texto>
			<pistas>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Diana</id-valor1>
					<id-dimension2>Isla</id-dimension2>
					<id-valor2>Lanzarote</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>La que va a volar con Sabena pasar\u00E1 siete d\u00EDas en su isla elegida</texto>
			<pistas>
				<pista>
					<id-dimension1>Compa\u00F1ia</id-dimension1>
					<id-valor1>Sabena</id-valor1>
					<id-dimension2>D\u00EDas</id-dimension2>
					<id-valor2>7</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Lufthansa es la compa\u00F1\u00EDa elegida por la que viajar\u00E1 a Tenerife</texto>
			<pistas>
				<pista>
					<id-dimension1>Compa\u00F1ia</id-dimension1>
					<id-valor1>Lufthansa</id-valor1>
					<id-dimension2>Isla</id-dimension2>
					<id-valor2>Tenerife</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien volar\u00E1 con Air France cuenta con 15 d\u00EDas de descanso</texto>
			<pistas>
				<pista>
					<id-dimension1>Compa\u00F1ia</id-dimension1>
					<id-valor1>Air France</id-valor1>
					<id-dimension2>D\u00EDas</id-dimension2>
					<id-valor2>15</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Carolina se tomar\u00E1 diez d\u00EDas de relax</texto>
			<pistas>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Carolina</id-valor1>
					<id-dimension2>D\u00EDas</id-dimension2>
					<id-valor2>10</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien viajar\u00E1 con Iberia se ha reservado m\u00E1s d\u00EDas que quien viajar\u00E1 a Mallorca</texto>
			<pistas>
				<pista>
					<id-dimension1>Compa\u00F1ia</id-dimension1>
					<id-valor1>Iberia</id-valor1>
					<id-dimension2>D\u00EDas</id-dimension2>
					<id-valor2>7</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Isla</id-dimension1>
					<id-valor1>Mallorca</id-valor1>
					<id-dimension2>D\u00EDas</id-dimension2>
					<id-valor2>15</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Luisa no piensa ir a Ibiza</texto>
			<pistas>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Luisa</id-valor1>
					<id-dimension2>Isla</id-dimension2>
					<id-valor2>Ibiza</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Mar\u00EDa (que no visitar\u00E1 Tenerife) tiene programados 14 d\u00EDas de ocio</texto>
			<pistas>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Mar\u00EDa</id-valor1>
					<id-dimension2>Isla</id-dimension2>
					<id-valor2>Tenerife</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Mar\u00EDa</id-valor1>
					<id-dimension2>D\u00EDas</id-dimension2>
					<id-valor2>14</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
	</pistas-del-juego>
</juego>

=== SantiagoDalchiele/logicgame/recursos/juegos/16-juegos-infantiles.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<juego xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/juego-logica.xsd">
	<id>16</id>
	<titulo>Juegos infantiles</titulo>
	<texto>Descubre cual es el juguete preferido de cada ni\u00F1o, de que color es y donde le gusta jugar</texto>
	<costo>50</costo>
	<dimensiones>
		<dimension>
			<id>Nombre</id>
			<valores>
				<valor>Luis</valor>
				<valor>Mat\u00EDas</valor>
				<valor>Renzo</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Juguete</id>
			<valores>
				<valor>Cami\u00F3n</valor>
				<valor>Pelota</valor>
				<valor>Mu\u00F1eco</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Color</id>
			<valores>
				<valor>Rojo</valor>
				<valor>Verde</valor>
				<valor>Azul</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Lugar</id>
			<valores>
				<valor>Living</valor>
				<valor>Dormitorio</valor>
				<valor>Patio</valor>
			</valores>
		</dimension>
	</dimensiones>
	<pistas-del-juego>
		<pista-del-juego>
			<texto>A Luis le gusta jugar con su pelota</texto>
			<pistas>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Luis</id-valor1>
					<id-dimension2>Juguete</id-dimension2>
					<id-valor2>Pelota</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Mat\u00EDas prefiere el juguete de color verde</texto>
			<pistas>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Mat\u00EDas</id-valor1>
					<id-dimension2>Color</id-dimension2>
					<id-valor2>Verde</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien prefiere el mu\u00F1eco (que es de color rojo), no le gusta jugar en el dormitorio</texto>
			<pistas>
				<pista>
					<id-dimension1>Juguete</id-dimension1>
					<id-valor1>Mu\u00F1eco</id-valor1>
					<id-dimension2>Color</id-dimension2>
					<id-valor2>Rojo</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Lugar</id-dimension1>
					<id-valor1>Dormitorio</id-valor1>
					<id-dimension2>Juguete</id-dimension2>
					<id-valor2>Mu\u00F1eco</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El ni\u00F1o que juega en el patio prefiere hacerlo con su pelota</texto>
			<pistas>
				<pista>
					<id-dimension1>Juguete</id-dimension1>
					<id-valor1>Pelota</id-valor1>
					<id-dimension2>Lugar</id-dimension2>
					<id-valor2>Patio</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
	</pistas-del-juego>
</juego>

=== SantiagoDalchiele/logicgame/recursos/juegos/06-museos.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<juego xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/juego-logica.xsd">
	<id>6</id>
	<titulo>¡Vamos al museo!</titulo>
	<texto>Antoñito Desastres ha vuelto a casa después de visitar varios museos. En todos ellos ha recogido folletos informativos, pero no los ha leído hasta llegar a su casa, durante el desayuno. Pero, claro, él es un poco desastre y ha tirado todo el chocolate por la mesa, manchando los folletos. Ahora no puede leer las informaciones que necesita para su tesis en la universidad. ¿Puedes ayudarle a organizar correctamente los siguientes datos?</texto>
	<costo>50</costo>
	<dimensiones>
		<dimension>
			<id>Museo</id>
			<valores>
				<valor>Centro Galego de Arte Contemporánea</valor>
				<valor>Museo Guggenheim</valor>
				<valor>Museo Nacional de Arte Romano</valor>
				<valor>Museu d´Art Contemporani</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Ciudad</id>
			<valores>
				<valor>Barcelona</valor>
				<valor>Bilbao</valor>
				<valor>Mérida</valor>
				<valor>Santiago de Compostela</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Arquitecto</id>
			<valores>
				<valor>Álvaro Siza</valor>
				<valor>Frank O. Gehry</valor>
				<valor>Rafael Moneo</valor>
				<valor>Richard Meier</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Año</id>
			<valores>
				<valor>1985</valor>
				<valor>1990</valor>
				<valor>1995</valor>
				<valor>1997</valor>
			</valores>
		</dimension>
	</dimensiones>
	<pistas-del-juego>
		<pista-del-juego>
			<texto>Moneo hizo en 1985 un museo en España</texto>
			<pistas>
				<pista>
					<id-dimension1>Arquitecto</id-dimension1>
					<id-valor1>Rafael Moneo</id-valor1>
					<id-dimension2>Año</id-dimension2>
					<id-valor2>1985</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El museo que está en Bilbao se construyó en 1997</texto>
			<pistas>
				<pista>
					<id-dimension1>Ciudad</id-dimension1>
					<id-valor1>Bilbao</id-valor1>
					<id-dimension2>Año</id-dimension2>
					<id-valor2>1997</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El Museu d´Art Contemporani de Barcelona se hizo en 1995</texto>
			<pistas>
				<pista>
					<id-dimension1>Museo</id-dimension1>
					<id-valor1>Museu d´Art Contemporani</id-valor1>
					<id-dimension2>Ciudad</id-dimension2>
					<id-valor2>Barcelona</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Museo</id-dimension1>
					<id-valor1>Museu d´Art Contemporani</id-valor1>
					<id-dimension2>Año</id-dimension2>
					<id-valor2>1995</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Ciudad</id-dimension1>
					<id-valor1>Barcelona</id-valor1>
					<id-dimension2>Año</id-dimension2>
					<id-valor2>1995</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El Museo Guggenheim es el más nuevo</texto>
			<pistas>
				<pista>
					<id-dimension1>Museo</id-dimension1>
					<id-valor1>Museo Guggenheim</id-valor1>
					<id-dimension2>Año</id-dimension2>
					<id-valor2>1997</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Richard Meier trabajó en Cataluña</texto>
			<pistas>
				<pista>
					<id-dimension1>Arquitecto</id-dimension1>
					<id-valor1>Richard Meier</id-valor1>
					<id-dimension2>Ciudad</id-dimension2>
					<id-valor2>Barcelona</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>En Mérida se encuentra el museo que hizo Rafael Moneo</texto>
			<pistas>
				<pista>
					<id-dimension1>Ciudad</id-dimension1>
					<id-valor1>Mérida</id-valor1>
					<id-dimension2>Arquitecto</id-dimension2>
					<id-valor2>Rafael Moneo</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>El Centro Galego de Arte Contemporánea se hizo en 1990</texto>
			<pistas>
				<pista>
					<id-dimension1>Museo</id-dimension1>
					<id-valor1>Centro Galego de Arte Contemporánea</id-valor1>
					<id-dimension2>Año</id-dimension2>
					<id-valor2>1990</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Frank O. Gehry trabajó en Bilbao</texto>
			<pistas>
				<pista>
					<id-dimension1>Arquitecto</id-dimension1>
					<id-valor1>Frank O. Gehry</id-valor1>
					<id-dimension2>Ciudad</id-dimension2>
					<id-valor2>Bilbao</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>De estos cuatro museos, el primero que se hizo fue el Museo Nacional de Arte Romano</texto>
			<pistas>
				<pista>
					<id-dimension1>Museo</id-dimension1>
					<id-valor1>Museo Nacional de Arte Romano</id-valor1>
					<id-dimension2>Año</id-dimension2>
					<id-valor2>1985</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>En 1990 Álvaro Siza trabajó en Santiago de Compostela</texto>
			<pistas>
				<pista>
					<id-dimension1>Año</id-dimension1>
					<id-valor1>1990</id-valor1>
					<id-dimension2>Arquitecto</id-dimension2>
					<id-valor2>Álvaro Siza</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Año</id-dimension1>
					<id-valor1>1990</id-valor1>
					<id-dimension2>Ciudad</id-dimension2>
					<id-valor2>Santiago de Compostela</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Arquitecto</id-dimension1>
					<id-valor1>Álvaro Siza</id-valor1>
					<id-dimension2>Ciudad</id-dimension2>
					<id-valor2>Santiago de Compostela</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
	</pistas-del-juego>
</juego>

=== SantiagoDalchiele/logicgame/recursos/juegos/15-problemas-en-la-vivienda.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<juego xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/juego-logica.xsd">
	<id>15</id>
	<titulo>Problemas en la vivienda</titulo>
	<texto>Mónica, Claudia y Laura están teniendo problemas en sus viviendas.  Descubre en que tipo de vivienda vive cada uno que tipo de problemas tienen y en que habitación</texto>
	<costo>48</costo>
	<dimensiones>
		<dimension>
			<id>nombre</id>
			<valores>
				<valor>Mónica</valor>
				<valor>Claudia</valor>
				<valor>Laura</valor>
			</valores>
		</dimension>
		<dimension>
			<id>vivienda</id>
			<valores>
				<valor>apartamento</valor>
				<valor>casa</valor>
				<valor>loft</valor>
			</valores>
		</dimension>
		<dimension>
			<id>habitación</id>
			<valores>
				<valor>baño</valor>
				<valor>cocina</valor>
				<valor>dormitorio</valor>
			</valores>
		</dimension>
		<dimension>
			<id>problema</id>
			<valores>
				<valor>caño roto</valor>
				<valor>humedad</valor>
				<valor>eléctricos</valor>
			</valores>
		</dimension>
	</dimensiones>
	<pistas-del-juego>
		<pista-del-juego>
			<texto>Mónica tiene problemas eléctricos pero no en el baño</texto>
			<pistas>
				<pista>
					<id-dimension1>nombre</id-dimension1>
					<id-valor1>Mónica</id-valor1>
					<id-dimension2>problema</id-dimension2>
					<id-valor2>eléctricos</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>habitación</id-dimension1>
					<id-valor1>baño</id-valor1>
					<id-dimension2>nombre</id-dimension2>
					<id-valor2>Mónica</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Claudia no es quien tiene problemas con el caño roto ni vive en una casa</texto>
			<pistas>
				<pista>
					<id-dimension1>nombre</id-dimension1>
					<id-valor1>Claudia</id-valor1>
					<id-dimension2>problema</id-dimension2>
					<id-valor2>caño roto</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>vivienda</id-dimension1>
					<id-valor1>casa</id-valor1>
					<id-dimension2>nombre</id-dimension2>
					<id-valor2>Claudia</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Laura no vive en casa ni tiene problemas en su cocina</texto>
			<pistas>
				<pista>
					<id-dimension1>nombre</id-dimension1>
					<id-valor1>Laura</id-valor1>
					<id-dimension2>vivienda</id-dimension2>
					<id-valor2>casa</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>nombre</id-dimension1>
					<id-valor1>Laura</id-valor1>
					<id-dimension2>habitación</id-dimension2>
					<id-valor2>cocina</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien tiene problemas de humedad no los tiene el dormitorio ni vive en un loft</texto>
			<pistas>
				<pista>
					<id-dimension1>problema</id-dimension1>
					<id-valor1>humedad</id-valor1>
					<id-dimension2>vivienda</id-dimension2>
					<id-valor2>loft</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>problema</id-dimension1>
					<id-valor1>humedad</id-valor1>
					<id-dimension2>habitación</id-dimension2>
					<id-valor2>dormitorio</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien vive en un apartamento no tiene problemas en su cocina</texto>
			<pistas>
				<pista>
					<id-dimension1>vivienda</id-dimension1>
					<id-valor1>apartamento</id-valor1>
					<id-dimension2>habitación</id-dimension2>
					<id-valor2>cocina</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien vive en un loft tiene un caño roto</texto>
			<pistas>
				<pista>
					<id-dimension1>vivienda</id-dimension1>
					<id-valor1>loft</id-valor1>
					<id-dimension2>problema</id-dimension2>
					<id-valor2>caño roto</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
	</pistas-del-juego>
</juego>

=== SantiagoDalchiele/logicgame/recursos/juegos/18-comensales.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<juego xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/juego-logica.xsd">
	<id>18</id>
	<titulo>Comensales</titulo>
	<texto>Descubre que comió y que bebida tomó cada uno de los comensales, y en que lugar disfrutaron de sus alimentos</texto>
	<costo>95</costo>
	<dimensiones>
		<dimension>
			<id>Nombre</id>
			<valores>
				<valor>Miguel</valor>
				<valor>Luciana</valor>
				<valor>Julia</valor>
				<valor>Natalia</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Comida</id>
			<valores>
				<valor>lasagna</valor>
				<valor>arroz con pollo</valor>
				<valor>pescado</valor>
				<valor>papas fritas</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Bebida</id>
			<valores>
				<valor>Coca-Cola</valor>
				<valor>agua mineral</valor>
				<valor>vino</valor>
				<valor>cerveza</valor>
			</valores>
		</dimension>
		<dimension>
			<id>Lugar</id>
			<valores>
				<valor>bar</valor>
				<valor>restaurant</valor>
				<valor>cantina</valor>
				<valor>casa</valor>
			</valores>
		</dimension>
	</dimensiones>
	<pistas-del-juego>
		<pista-del-juego>
			<texto>Quien prefirió las papas fritas no lo hizo en un restaurant</texto>
			<pistas>
				<pista>
					<id-dimension1>Lugar</id-dimension1>
					<id-valor1>restaurant</id-valor1>
					<id-dimension2>Comida</id-dimension2>
					<id-valor2>papas fritas</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Julia disfrutó de su comida en su propia casa</texto>
			<pistas>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Julia</id-valor1>
					<id-dimension2>Lugar</id-dimension2>
					<id-valor2>casa</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>A Miguel no le gusta el pescado</texto>
			<pistas>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Miguel</id-valor1>
					<id-dimension2>Comida</id-dimension2>
					<id-valor2>pescado</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien comió papas fritas no lo acompañó con Coca-Cola</texto>
			<pistas>
				<pista>
					<id-dimension1>Bebida</id-dimension1>
					<id-valor1>Coca-Cola</id-valor1>
					<id-dimension2>Comida</id-dimension2>
					<id-valor2>papas fritas</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Quien disfrutó de la lasagna lo hizo con una copa de vino</texto>
			<pistas>
				<pista>
					<id-dimension1>Bebida</id-dimension1>
					<id-valor1>vino</id-valor1>
					<id-dimension2>Comida</id-dimension2>
					<id-valor2>lasagna</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Natalia bebió cerveza, pero no fue ni en un bar ni en un restaurant</texto>
			<pistas>
				<pista>
					<id-dimension1>Bebida</id-dimension1>
					<id-valor1>cerveza</id-valor1>
					<id-dimension2>Lugar</id-dimension2>
					<id-valor2>bar</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Bebida</id-dimension1>
					<id-valor1>cerveza</id-valor1>
					<id-dimension2>Lugar</id-dimension2>
					<id-valor2>restaurant</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
				<pista>
					<id-dimension1>Nombre</id-dimension1>
					<id-valor1>Natalia</id-valor1>
					<id-dimension2>Bebida</id-dimension2>
					<id-valor2>cerveza</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Luciana optó por comer arroz con pollo</texto>
			<pistas>
				<pista>
					<id-dimension1>Comida</id-dimension1>
					<id-valor1>arroz con pollo</id-valor1>
					<id-dimension2>Nombre</id-dimension2>
					<id-valor2>Luciana</id-valor2>
					<afirma-niega>true</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
		<pista-del-juego>
			<texto>Miguel no comió lasagna</texto>
			<pistas>
				<pista>
					<id-dimension1>Comida</id-dimension1>
					<id-valor1>lasagna</id-valor1>
					<id-dimension2>Nombre</id-dimension2>
					<id-valor2>Miguel</id-valor2>
					<afirma-niega>false</afirma-niega>
				</pista>
			</pistas>
		</pista-del-juego>
	</pistas-del-juego>
</juego>
